### ISSUE TITLE
Broken contribution link

### ISSUE THREAD

**Issue by Abrasha** [playframework/playframework.com#171] opened 2017-09-22 09:02 UTC
Steps to reproduce:
- Go to https://www.playframework.com/documentation/2.6.x/ScalaJson
- Navigate to the bottom
- Click on `here`

Link address is https://github.com/playframework/playframework/edit/2.6.x/documentation/manual/working/scalaGuide/main/json/ScalaJson.md

I am not sure that it relates only to this page. But at least the same behavior is for https://www.playframework.com/documentation/2.6.x/ScalaJsonCombinators

**Comment by Dulya** [comment] 2017-10-10 05:38
Possibly this issue is referenced here #86

**Comment by gmethvin** [comment] 2017-10-11 21:59
yeah this is a duplicate of #86

**Closed by gmethvin** 2017-10-11 21:59 UTC
