### ISSUE TITLE
Erroneous link to documentation on GH

### ISSUE THREAD

**Issue by BjornHamels** [playframework/playframework.com#42] opened 2015-10-29 11:13 UTC
On the bottom of [this](https://www.playframework.com/documentation/2.5.x/ScalaAnorm) ScalaAnorm page there's the following text to direct to GH: `Found an error in this documentation? The source code for this page can be found here` where `here` links to the non-existent page: https://github.com/playframework/playframework/blob/master/documentation/manual/working/scalaGuide/main/sql/ScalaAnorm.md
This should be linking to: https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/ScalaAnorm.md I'd guess.

**Comment by gmethvin** [comment] 2016-06-19 11:15
Realized this is a dupe of #86 (it's an error for all the non-playframework repos).

**Closed by gmethvin** 2016-06-19 11:15 UTC
